const menu = [
    {
      id: 1,
      title: 'Cat-grill',
      category: 'grilled',
      price: 15.99,
      img: './images/cat-meat.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'Crocs- Grill',
      category: 'grilled',
      price: 59.99,
      img: './images/crocs.webp',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'Frog-Roast',
      category: 'roast',
      price: 6.99,
      img: './images/Frog.jpeg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'HotDog',
      category: 'grilled',
      price: 20.99,
      img: './images/hotdog.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'Pig-Head',
      category: 'roast',
      price: 22.99,
      img: './images/pig.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'Rats-roast',
      category: 'roast',
      price: 18.99,
      img: './images/rats.jpeg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'snails',
      category: 'boiled',
      price: 8.99,
      img: './images/snails.webp',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'Snake',
      category: 'roast',
      price: 12.99,
      img: './images/snake.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'Turtle',
      category: 'boiled',
      price: 16.99,
      img: './images/turtle.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;